/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/player_y

// This file generated by ModelGen - Do NOT Modify

#ifndef M_ACTOR_H
#define M_ACTOR_H

struct edict_s;
typedef struct edict_s edict_t;

typedef struct cplane_s cplane_t;
typedef struct csurface_s csurface_t;
typedef float vec3_t[3];

// misc_actor spawnflags
#define ACTOR_SPAWNFLAG_AMBUSH              0x00000001
#define ACTOR_SPAWNFLAG_TRIGGER_SPAWN       0x00000002
#define ACTOR_SPAWNFLAG_SIGHT               0x00000004
#define ACTOR_SPAWNFLAG_CORPSE              0x00000008
#define ACTOR_SPAWNFLAG_START_ON            0x00000020
#define ACTOR_SPAWNFLAG_WIMPY               0x00000040

// target_actor spawnflags
#define TARGET_ACTOR_FLAG_JUMP              0x00000001
#define TARGET_ACTOR_FLAG_SHOOT             0x00000002
#define TARGET_ACTOR_FLAG_ATTACK            0x00000004
#define TARGET_ACTOR_FLAG_HOLD              0x00000010
#define TARGET_ACTOR_FLAG_BRUTAL            0x00000020

typedef enum actor_path_state_e
{
        ACTOR_PATH_STATE_IDLE = 0,
        ACTOR_PATH_STATE_SEEKING,
        ACTOR_PATH_STATE_WAITING,
        ACTOR_PATH_STATE_SCRIPT_WAIT,
        ACTOR_PATH_STATE_LOCKED
} actor_path_state_t;


// Mission actor helpers
void actor_stand (edict_t *self);
void actor_walk (edict_t *self);
void actor_run (edict_t *self);
void actor_pain (edict_t *self, edict_t *other, float kick, int damage);
void actor_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point);
void actor_attack (edict_t *self);
void actorMachineGun (edict_t *self);
void actor_fire (edict_t *self);
void actor_dead (edict_t *self);
void actor_use (edict_t *self, edict_t *other, edict_t *activator);
void target_actor_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf);

void SP_misc_actor (edict_t *self);
void Actor_PostLoad (edict_t *self);
void SP_target_actor (edict_t *self);

#endif /* M_ACTOR_H */
